// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the accounts defined in the IDL.

package solana

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyAccount(accountData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek account discriminator: %w", err)
	}
	switch discriminator {
	case Account_Connection:
		value := new(Connection)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Connection: %w", err)
		}
		return value, nil
	case Account_ProtocolConfig:
		value := new(ProtocolConfig)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as ProtocolConfig: %w", err)
		}
		return value, nil
	case Account_Seeker:
		value := new(Seeker)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Seeker: %w", err)
		}
		return value, nil
	case Account_Warden:
		value := new(Warden)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Warden: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseAccount_Connection(accountData []byte) (*Connection, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Connection {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Connection, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Connection)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Connection: %w", err)
	}
	return acc, nil
}

func ParseAccount_ProtocolConfig(accountData []byte) (*ProtocolConfig, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_ProtocolConfig {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_ProtocolConfig, binary.FormatDiscriminator(discriminator))
	}
	acc := new(ProtocolConfig)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type ProtocolConfig: %w", err)
	}
	return acc, nil
}

func ParseAccount_Seeker(accountData []byte) (*Seeker, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Seeker {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Seeker, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Seeker)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Seeker: %w", err)
	}
	return acc, nil
}

func ParseAccount_Warden(accountData []byte) (*Warden, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Warden {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Warden, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Warden)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Warden: %w", err)
	}
	return acc, nil
}
