// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package solana

// Account discriminators
var (
	Account_Connection     = [8]byte{209, 186, 115, 58, 36, 236, 179, 10}
	Account_ProtocolConfig = [8]byte{207, 91, 250, 28, 152, 179, 215, 209}
	Account_Seeker         = [8]byte{106, 201, 97, 118, 1, 110, 224, 133}
	Account_Warden         = [8]byte{73, 11, 82, 46, 202, 0, 179, 133}
)

// Event discriminators
var (
	Event_ArkhamMintInitialized      = [8]byte{24, 177, 72, 228, 14, 191, 164, 189}
	Event_BandwidthProofSubmitted    = [8]byte{73, 164, 55, 174, 238, 117, 228, 8}
	Event_ConnectionEnded            = [8]byte{155, 105, 4, 133, 186, 109, 217, 137}
	Event_ConnectionStarted          = [8]byte{253, 72, 159, 233, 126, 6, 248, 3}
	Event_EarningsClaimed            = [8]byte{106, 170, 154, 105, 21, 43, 189, 97}
	Event_EscrowDeposited            = [8]byte{28, 193, 105, 27, 40, 101, 65, 211}
	Event_PremiumPoolRankingsUpdated = [8]byte{109, 220, 21, 16, 82, 23, 122, 27}
	Event_ProtocolConfigInitialized  = [8]byte{243, 69, 27, 238, 111, 169, 87, 231}
	Event_ProtocolConfigUpdated      = [8]byte{20, 99, 32, 237, 111, 86, 195, 199}
	Event_ReputationUpdated          = [8]byte{26, 36, 187, 150, 235, 90, 106, 89}
	Event_SubsidiesDistributed       = [8]byte{133, 199, 129, 213, 115, 186, 210, 0}
	Event_TokensClaimed              = [8]byte{25, 128, 244, 55, 241, 136, 200, 91}
	Event_UnstakeRequested           = [8]byte{21, 253, 177, 85, 129, 206, 42, 152}
	Event_WardenPeerIdUpdated        = [8]byte{156, 137, 28, 149, 212, 101, 74, 224}
	Event_WardenRegistered           = [8]byte{131, 190, 122, 62, 145, 152, 187, 227}
	Event_WardenUnstaked             = [8]byte{150, 7, 246, 105, 220, 235, 137, 32}
)

// Instruction discriminators
var (
	Instruction_ClaimArkhamTokens         = [8]byte{180, 14, 137, 225, 247, 246, 242, 200}
	Instruction_ClaimEarnings             = [8]byte{49, 99, 161, 170, 22, 233, 54, 140}
	Instruction_ClaimUnstake              = [8]byte{172, 113, 117, 178, 223, 245, 247, 118}
	Instruction_CloseProtocolConfig       = [8]byte{203, 147, 4, 67, 17, 28, 203, 219}
	Instruction_DepositEscrow             = [8]byte{226, 112, 158, 176, 178, 118, 153, 128}
	Instruction_DistributeSubsidies       = [8]byte{38, 141, 106, 248, 234, 99, 180, 91}
	Instruction_EndConnection             = [8]byte{145, 116, 162, 199, 86, 180, 63, 42}
	Instruction_Initialize                = [8]byte{175, 175, 109, 31, 13, 152, 155, 237}
	Instruction_InitializeArkhamMint      = [8]byte{199, 33, 247, 30, 147, 49, 100, 72}
	Instruction_InitializeProtocolConfig  = [8]byte{28, 50, 43, 233, 244, 98, 123, 118}
	Instruction_InitializeWarden          = [8]byte{208, 228, 42, 148, 121, 54, 243, 65}
	Instruction_MigrateProtocolConfig     = [8]byte{240, 133, 241, 218, 118, 253, 139, 28}
	Instruction_StartConnection           = [8]byte{27, 34, 208, 176, 138, 230, 238, 74}
	Instruction_SubmitBandwidthProof      = [8]byte{98, 96, 38, 149, 163, 54, 248, 15}
	Instruction_UnstakeWarden             = [8]byte{224, 104, 75, 109, 242, 42, 150, 156}
	Instruction_UpdatePremiumPoolRankings = [8]byte{159, 191, 184, 117, 40, 215, 186, 36}
	Instruction_UpdateProtocolConfig      = [8]byte{197, 97, 123, 54, 221, 168, 11, 135}
	Instruction_UpdateReputation          = [8]byte{194, 220, 43, 201, 54, 209, 49, 178}
	Instruction_UpdateWardenPeerId        = [8]byte{53, 54, 40, 214, 85, 8, 247, 105}
)
