// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the events defined in the IDL.

package solana

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyEvent(eventData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek event discriminator: %w", err)
	}
	switch discriminator {
	case Event_ArkhamMintInitialized:
		value := new(ArkhamMintInitialized)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as ArkhamMintInitialized: %w", err)
		}
		return value, nil
	case Event_BandwidthProofSubmitted:
		value := new(BandwidthProofSubmitted)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as BandwidthProofSubmitted: %w", err)
		}
		return value, nil
	case Event_ConnectionEnded:
		value := new(ConnectionEnded)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as ConnectionEnded: %w", err)
		}
		return value, nil
	case Event_ConnectionStarted:
		value := new(ConnectionStarted)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as ConnectionStarted: %w", err)
		}
		return value, nil
	case Event_EarningsClaimed:
		value := new(EarningsClaimed)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as EarningsClaimed: %w", err)
		}
		return value, nil
	case Event_EscrowDeposited:
		value := new(EscrowDeposited)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as EscrowDeposited: %w", err)
		}
		return value, nil
	case Event_PremiumPoolRankingsUpdated:
		value := new(PremiumPoolRankingsUpdated)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as PremiumPoolRankingsUpdated: %w", err)
		}
		return value, nil
	case Event_ProtocolConfigInitialized:
		value := new(ProtocolConfigInitialized)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as ProtocolConfigInitialized: %w", err)
		}
		return value, nil
	case Event_ProtocolConfigUpdated:
		value := new(ProtocolConfigUpdated)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as ProtocolConfigUpdated: %w", err)
		}
		return value, nil
	case Event_ReputationUpdated:
		value := new(ReputationUpdated)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as ReputationUpdated: %w", err)
		}
		return value, nil
	case Event_SubsidiesDistributed:
		value := new(SubsidiesDistributed)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SubsidiesDistributed: %w", err)
		}
		return value, nil
	case Event_TokensClaimed:
		value := new(TokensClaimed)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as TokensClaimed: %w", err)
		}
		return value, nil
	case Event_UnstakeRequested:
		value := new(UnstakeRequested)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as UnstakeRequested: %w", err)
		}
		return value, nil
	case Event_WardenPeerIdUpdated:
		value := new(WardenPeerIdUpdated)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as WardenPeerIdUpdated: %w", err)
		}
		return value, nil
	case Event_WardenRegistered:
		value := new(WardenRegistered)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as WardenRegistered: %w", err)
		}
		return value, nil
	case Event_WardenUnstaked:
		value := new(WardenUnstaked)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as WardenUnstaked: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseEvent_ArkhamMintInitialized(eventData []byte) (*ArkhamMintInitialized, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_ArkhamMintInitialized {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_ArkhamMintInitialized, binary.FormatDiscriminator(discriminator))
	}
	event := new(ArkhamMintInitialized)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type ArkhamMintInitialized: %w", err)
	}
	return event, nil
}

func ParseEvent_BandwidthProofSubmitted(eventData []byte) (*BandwidthProofSubmitted, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_BandwidthProofSubmitted {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_BandwidthProofSubmitted, binary.FormatDiscriminator(discriminator))
	}
	event := new(BandwidthProofSubmitted)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type BandwidthProofSubmitted: %w", err)
	}
	return event, nil
}

func ParseEvent_ConnectionEnded(eventData []byte) (*ConnectionEnded, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_ConnectionEnded {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_ConnectionEnded, binary.FormatDiscriminator(discriminator))
	}
	event := new(ConnectionEnded)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type ConnectionEnded: %w", err)
	}
	return event, nil
}

func ParseEvent_ConnectionStarted(eventData []byte) (*ConnectionStarted, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_ConnectionStarted {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_ConnectionStarted, binary.FormatDiscriminator(discriminator))
	}
	event := new(ConnectionStarted)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type ConnectionStarted: %w", err)
	}
	return event, nil
}

func ParseEvent_EarningsClaimed(eventData []byte) (*EarningsClaimed, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_EarningsClaimed {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_EarningsClaimed, binary.FormatDiscriminator(discriminator))
	}
	event := new(EarningsClaimed)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type EarningsClaimed: %w", err)
	}
	return event, nil
}

func ParseEvent_EscrowDeposited(eventData []byte) (*EscrowDeposited, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_EscrowDeposited {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_EscrowDeposited, binary.FormatDiscriminator(discriminator))
	}
	event := new(EscrowDeposited)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type EscrowDeposited: %w", err)
	}
	return event, nil
}

func ParseEvent_PremiumPoolRankingsUpdated(eventData []byte) (*PremiumPoolRankingsUpdated, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_PremiumPoolRankingsUpdated {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_PremiumPoolRankingsUpdated, binary.FormatDiscriminator(discriminator))
	}
	event := new(PremiumPoolRankingsUpdated)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type PremiumPoolRankingsUpdated: %w", err)
	}
	return event, nil
}

func ParseEvent_ProtocolConfigInitialized(eventData []byte) (*ProtocolConfigInitialized, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_ProtocolConfigInitialized {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_ProtocolConfigInitialized, binary.FormatDiscriminator(discriminator))
	}
	event := new(ProtocolConfigInitialized)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type ProtocolConfigInitialized: %w", err)
	}
	return event, nil
}

func ParseEvent_ProtocolConfigUpdated(eventData []byte) (*ProtocolConfigUpdated, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_ProtocolConfigUpdated {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_ProtocolConfigUpdated, binary.FormatDiscriminator(discriminator))
	}
	event := new(ProtocolConfigUpdated)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type ProtocolConfigUpdated: %w", err)
	}
	return event, nil
}

func ParseEvent_ReputationUpdated(eventData []byte) (*ReputationUpdated, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_ReputationUpdated {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_ReputationUpdated, binary.FormatDiscriminator(discriminator))
	}
	event := new(ReputationUpdated)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type ReputationUpdated: %w", err)
	}
	return event, nil
}

func ParseEvent_SubsidiesDistributed(eventData []byte) (*SubsidiesDistributed, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SubsidiesDistributed {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SubsidiesDistributed, binary.FormatDiscriminator(discriminator))
	}
	event := new(SubsidiesDistributed)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SubsidiesDistributed: %w", err)
	}
	return event, nil
}

func ParseEvent_TokensClaimed(eventData []byte) (*TokensClaimed, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_TokensClaimed {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_TokensClaimed, binary.FormatDiscriminator(discriminator))
	}
	event := new(TokensClaimed)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type TokensClaimed: %w", err)
	}
	return event, nil
}

func ParseEvent_UnstakeRequested(eventData []byte) (*UnstakeRequested, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_UnstakeRequested {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_UnstakeRequested, binary.FormatDiscriminator(discriminator))
	}
	event := new(UnstakeRequested)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type UnstakeRequested: %w", err)
	}
	return event, nil
}

func ParseEvent_WardenPeerIdUpdated(eventData []byte) (*WardenPeerIdUpdated, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_WardenPeerIdUpdated {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_WardenPeerIdUpdated, binary.FormatDiscriminator(discriminator))
	}
	event := new(WardenPeerIdUpdated)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type WardenPeerIdUpdated: %w", err)
	}
	return event, nil
}

func ParseEvent_WardenRegistered(eventData []byte) (*WardenRegistered, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_WardenRegistered {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_WardenRegistered, binary.FormatDiscriminator(discriminator))
	}
	event := new(WardenRegistered)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type WardenRegistered: %w", err)
	}
	return event, nil
}

func ParseEvent_WardenUnstaked(eventData []byte) (*WardenUnstaked, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_WardenUnstaked {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_WardenUnstaked, binary.FormatDiscriminator(discriminator))
	}
	event := new(WardenUnstaked)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type WardenUnstaked: %w", err)
	}
	return event, nil
}
