// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package solana

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("B85X9aTrpWAdi1xhLvPmDPuYmfz5YdMd9X8qr7uU4H18")
