// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package solana

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type ArkhamMintInitialized struct {
	Authority solanago.PublicKey `json:"authority"`
	Mint      solanago.PublicKey `json:"mint"`
}

func (obj ArkhamMintInitialized) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	return nil
}

func (obj ArkhamMintInitialized) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ArkhamMintInitialized: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ArkhamMintInitialized) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	return nil
}

func (obj *ArkhamMintInitialized) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ArkhamMintInitialized: %w", err)
	}
	return nil
}

func UnmarshalArkhamMintInitialized(buf []byte) (*ArkhamMintInitialized, error) {
	obj := new(ArkhamMintInitialized)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type BandwidthProof struct {
	Timestamp       int64     `json:"timestamp"`
	MbConsumed      uint64    `json:"mbConsumed"`
	SeekerSignature [64]uint8 `json:"seekerSignature"`
	WardenSignature [64]uint8 `json:"wardenSignature"`
}

func (obj BandwidthProof) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Serialize `MbConsumed`:
	err = encoder.Encode(obj.MbConsumed)
	if err != nil {
		return errors.NewField("MbConsumed", err)
	}
	// Serialize `SeekerSignature`:
	err = encoder.Encode(obj.SeekerSignature)
	if err != nil {
		return errors.NewField("SeekerSignature", err)
	}
	// Serialize `WardenSignature`:
	err = encoder.Encode(obj.WardenSignature)
	if err != nil {
		return errors.NewField("WardenSignature", err)
	}
	return nil
}

func (obj BandwidthProof) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding BandwidthProof: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *BandwidthProof) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	// Deserialize `MbConsumed`:
	err = decoder.Decode(&obj.MbConsumed)
	if err != nil {
		return errors.NewField("MbConsumed", err)
	}
	// Deserialize `SeekerSignature`:
	err = decoder.Decode(&obj.SeekerSignature)
	if err != nil {
		return errors.NewField("SeekerSignature", err)
	}
	// Deserialize `WardenSignature`:
	err = decoder.Decode(&obj.WardenSignature)
	if err != nil {
		return errors.NewField("WardenSignature", err)
	}
	return nil
}

func (obj *BandwidthProof) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling BandwidthProof: %w", err)
	}
	return nil
}

func UnmarshalBandwidthProof(buf []byte) (*BandwidthProof, error) {
	obj := new(BandwidthProof)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type BandwidthProofSubmitted struct {
	Connection    solanago.PublicKey `json:"connection"`
	MbConsumed    uint64             `json:"mbConsumed"`
	PaymentAmount uint64             `json:"paymentAmount"`
	ArkhamEarned  uint64             `json:"arkhamEarned"`
}

func (obj BandwidthProofSubmitted) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Connection`:
	err = encoder.Encode(obj.Connection)
	if err != nil {
		return errors.NewField("Connection", err)
	}
	// Serialize `MbConsumed`:
	err = encoder.Encode(obj.MbConsumed)
	if err != nil {
		return errors.NewField("MbConsumed", err)
	}
	// Serialize `PaymentAmount`:
	err = encoder.Encode(obj.PaymentAmount)
	if err != nil {
		return errors.NewField("PaymentAmount", err)
	}
	// Serialize `ArkhamEarned`:
	err = encoder.Encode(obj.ArkhamEarned)
	if err != nil {
		return errors.NewField("ArkhamEarned", err)
	}
	return nil
}

func (obj BandwidthProofSubmitted) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding BandwidthProofSubmitted: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *BandwidthProofSubmitted) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Connection`:
	err = decoder.Decode(&obj.Connection)
	if err != nil {
		return errors.NewField("Connection", err)
	}
	// Deserialize `MbConsumed`:
	err = decoder.Decode(&obj.MbConsumed)
	if err != nil {
		return errors.NewField("MbConsumed", err)
	}
	// Deserialize `PaymentAmount`:
	err = decoder.Decode(&obj.PaymentAmount)
	if err != nil {
		return errors.NewField("PaymentAmount", err)
	}
	// Deserialize `ArkhamEarned`:
	err = decoder.Decode(&obj.ArkhamEarned)
	if err != nil {
		return errors.NewField("ArkhamEarned", err)
	}
	return nil
}

func (obj *BandwidthProofSubmitted) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling BandwidthProofSubmitted: %w", err)
	}
	return nil
}

func UnmarshalBandwidthProofSubmitted(buf []byte) (*BandwidthProofSubmitted, error) {
	obj := new(BandwidthProofSubmitted)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Connection struct {
	Seeker            solanago.PublicKey `json:"seeker"`
	Warden            solanago.PublicKey `json:"warden"`
	StartedAt         int64              `json:"startedAt"`
	LastProofAt       int64              `json:"lastProofAt"`
	BandwidthConsumed uint64             `json:"bandwidthConsumed"`
	BandwidthProofs   []BandwidthProof   `json:"bandwidthProofs"`
	AmountEscrowed    uint64             `json:"amountEscrowed"`
	AmountPaid        uint64             `json:"amountPaid"`
	RatePerMb         uint64             `json:"ratePerMb"`
	WardenMultiplier  uint16             `json:"wardenMultiplier"`
}

func (obj Connection) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Seeker`:
	err = encoder.Encode(obj.Seeker)
	if err != nil {
		return errors.NewField("Seeker", err)
	}
	// Serialize `Warden`:
	err = encoder.Encode(obj.Warden)
	if err != nil {
		return errors.NewField("Warden", err)
	}
	// Serialize `StartedAt`:
	err = encoder.Encode(obj.StartedAt)
	if err != nil {
		return errors.NewField("StartedAt", err)
	}
	// Serialize `LastProofAt`:
	err = encoder.Encode(obj.LastProofAt)
	if err != nil {
		return errors.NewField("LastProofAt", err)
	}
	// Serialize `BandwidthConsumed`:
	err = encoder.Encode(obj.BandwidthConsumed)
	if err != nil {
		return errors.NewField("BandwidthConsumed", err)
	}
	// Serialize `BandwidthProofs`:
	err = encoder.Encode(obj.BandwidthProofs)
	if err != nil {
		return errors.NewField("BandwidthProofs", err)
	}
	// Serialize `AmountEscrowed`:
	err = encoder.Encode(obj.AmountEscrowed)
	if err != nil {
		return errors.NewField("AmountEscrowed", err)
	}
	// Serialize `AmountPaid`:
	err = encoder.Encode(obj.AmountPaid)
	if err != nil {
		return errors.NewField("AmountPaid", err)
	}
	// Serialize `RatePerMb`:
	err = encoder.Encode(obj.RatePerMb)
	if err != nil {
		return errors.NewField("RatePerMb", err)
	}
	// Serialize `WardenMultiplier`:
	err = encoder.Encode(obj.WardenMultiplier)
	if err != nil {
		return errors.NewField("WardenMultiplier", err)
	}
	return nil
}

func (obj Connection) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Connection: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Connection) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Seeker`:
	err = decoder.Decode(&obj.Seeker)
	if err != nil {
		return errors.NewField("Seeker", err)
	}
	// Deserialize `Warden`:
	err = decoder.Decode(&obj.Warden)
	if err != nil {
		return errors.NewField("Warden", err)
	}
	// Deserialize `StartedAt`:
	err = decoder.Decode(&obj.StartedAt)
	if err != nil {
		return errors.NewField("StartedAt", err)
	}
	// Deserialize `LastProofAt`:
	err = decoder.Decode(&obj.LastProofAt)
	if err != nil {
		return errors.NewField("LastProofAt", err)
	}
	// Deserialize `BandwidthConsumed`:
	err = decoder.Decode(&obj.BandwidthConsumed)
	if err != nil {
		return errors.NewField("BandwidthConsumed", err)
	}
	// Deserialize `BandwidthProofs`:
	err = decoder.Decode(&obj.BandwidthProofs)
	if err != nil {
		return errors.NewField("BandwidthProofs", err)
	}
	// Deserialize `AmountEscrowed`:
	err = decoder.Decode(&obj.AmountEscrowed)
	if err != nil {
		return errors.NewField("AmountEscrowed", err)
	}
	// Deserialize `AmountPaid`:
	err = decoder.Decode(&obj.AmountPaid)
	if err != nil {
		return errors.NewField("AmountPaid", err)
	}
	// Deserialize `RatePerMb`:
	err = decoder.Decode(&obj.RatePerMb)
	if err != nil {
		return errors.NewField("RatePerMb", err)
	}
	// Deserialize `WardenMultiplier`:
	err = decoder.Decode(&obj.WardenMultiplier)
	if err != nil {
		return errors.NewField("WardenMultiplier", err)
	}
	return nil
}

func (obj *Connection) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Connection: %w", err)
	}
	return nil
}

func UnmarshalConnection(buf []byte) (*Connection, error) {
	obj := new(Connection)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ConnectionEnded struct {
	Seeker            solanago.PublicKey `json:"seeker"`
	Warden            solanago.PublicKey `json:"warden"`
	BandwidthConsumed uint64             `json:"bandwidthConsumed"`
	TotalPaid         uint64             `json:"totalPaid"`
	Refunded          uint64             `json:"refunded"`
}

func (obj ConnectionEnded) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Seeker`:
	err = encoder.Encode(obj.Seeker)
	if err != nil {
		return errors.NewField("Seeker", err)
	}
	// Serialize `Warden`:
	err = encoder.Encode(obj.Warden)
	if err != nil {
		return errors.NewField("Warden", err)
	}
	// Serialize `BandwidthConsumed`:
	err = encoder.Encode(obj.BandwidthConsumed)
	if err != nil {
		return errors.NewField("BandwidthConsumed", err)
	}
	// Serialize `TotalPaid`:
	err = encoder.Encode(obj.TotalPaid)
	if err != nil {
		return errors.NewField("TotalPaid", err)
	}
	// Serialize `Refunded`:
	err = encoder.Encode(obj.Refunded)
	if err != nil {
		return errors.NewField("Refunded", err)
	}
	return nil
}

func (obj ConnectionEnded) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ConnectionEnded: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ConnectionEnded) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Seeker`:
	err = decoder.Decode(&obj.Seeker)
	if err != nil {
		return errors.NewField("Seeker", err)
	}
	// Deserialize `Warden`:
	err = decoder.Decode(&obj.Warden)
	if err != nil {
		return errors.NewField("Warden", err)
	}
	// Deserialize `BandwidthConsumed`:
	err = decoder.Decode(&obj.BandwidthConsumed)
	if err != nil {
		return errors.NewField("BandwidthConsumed", err)
	}
	// Deserialize `TotalPaid`:
	err = decoder.Decode(&obj.TotalPaid)
	if err != nil {
		return errors.NewField("TotalPaid", err)
	}
	// Deserialize `Refunded`:
	err = decoder.Decode(&obj.Refunded)
	if err != nil {
		return errors.NewField("Refunded", err)
	}
	return nil
}

func (obj *ConnectionEnded) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ConnectionEnded: %w", err)
	}
	return nil
}

func UnmarshalConnectionEnded(buf []byte) (*ConnectionEnded, error) {
	obj := new(ConnectionEnded)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ConnectionStarted struct {
	Seeker       solanago.PublicKey `json:"seeker"`
	Warden       solanago.PublicKey `json:"warden"`
	EstimatedMb  uint64             `json:"estimatedMb"`
	RatePerMb    uint64             `json:"ratePerMb"`
	EscrowAmount uint64             `json:"escrowAmount"`
}

func (obj ConnectionStarted) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Seeker`:
	err = encoder.Encode(obj.Seeker)
	if err != nil {
		return errors.NewField("Seeker", err)
	}
	// Serialize `Warden`:
	err = encoder.Encode(obj.Warden)
	if err != nil {
		return errors.NewField("Warden", err)
	}
	// Serialize `EstimatedMb`:
	err = encoder.Encode(obj.EstimatedMb)
	if err != nil {
		return errors.NewField("EstimatedMb", err)
	}
	// Serialize `RatePerMb`:
	err = encoder.Encode(obj.RatePerMb)
	if err != nil {
		return errors.NewField("RatePerMb", err)
	}
	// Serialize `EscrowAmount`:
	err = encoder.Encode(obj.EscrowAmount)
	if err != nil {
		return errors.NewField("EscrowAmount", err)
	}
	return nil
}

func (obj ConnectionStarted) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ConnectionStarted: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ConnectionStarted) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Seeker`:
	err = decoder.Decode(&obj.Seeker)
	if err != nil {
		return errors.NewField("Seeker", err)
	}
	// Deserialize `Warden`:
	err = decoder.Decode(&obj.Warden)
	if err != nil {
		return errors.NewField("Warden", err)
	}
	// Deserialize `EstimatedMb`:
	err = decoder.Decode(&obj.EstimatedMb)
	if err != nil {
		return errors.NewField("EstimatedMb", err)
	}
	// Deserialize `RatePerMb`:
	err = decoder.Decode(&obj.RatePerMb)
	if err != nil {
		return errors.NewField("RatePerMb", err)
	}
	// Deserialize `EscrowAmount`:
	err = decoder.Decode(&obj.EscrowAmount)
	if err != nil {
		return errors.NewField("EscrowAmount", err)
	}
	return nil
}

func (obj *ConnectionStarted) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ConnectionStarted: %w", err)
	}
	return nil
}

func UnmarshalConnectionStarted(buf []byte) (*ConnectionStarted, error) {
	obj := new(ConnectionStarted)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type EarningsClaimed struct {
	Authority  solanago.PublicKey `json:"authority"`
	Amount     uint64             `json:"amount"`
	UsePrivate bool               `json:"usePrivate"`
}

func (obj EarningsClaimed) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `Amount`:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Serialize `UsePrivate`:
	err = encoder.Encode(obj.UsePrivate)
	if err != nil {
		return errors.NewField("UsePrivate", err)
	}
	return nil
}

func (obj EarningsClaimed) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EarningsClaimed: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EarningsClaimed) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Deserialize `UsePrivate`:
	err = decoder.Decode(&obj.UsePrivate)
	if err != nil {
		return errors.NewField("UsePrivate", err)
	}
	return nil
}

func (obj *EarningsClaimed) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EarningsClaimed: %w", err)
	}
	return nil
}

func UnmarshalEarningsClaimed(buf []byte) (*EarningsClaimed, error) {
	obj := new(EarningsClaimed)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type EscrowDeposited struct {
	Authority  solanago.PublicKey `json:"authority"`
	Amount     uint64             `json:"amount"`
	UsePrivate bool               `json:"usePrivate"`
}

func (obj EscrowDeposited) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `Amount`:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Serialize `UsePrivate`:
	err = encoder.Encode(obj.UsePrivate)
	if err != nil {
		return errors.NewField("UsePrivate", err)
	}
	return nil
}

func (obj EscrowDeposited) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EscrowDeposited: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EscrowDeposited) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Deserialize `UsePrivate`:
	err = decoder.Decode(&obj.UsePrivate)
	if err != nil {
		return errors.NewField("UsePrivate", err)
	}
	return nil
}

func (obj *EscrowDeposited) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EscrowDeposited: %w", err)
	}
	return nil
}

func UnmarshalEscrowDeposited(buf []byte) (*EscrowDeposited, error) {
	obj := new(EscrowDeposited)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type GeoPremium struct {
	RegionCode uint8  `json:"regionCode"`
	PremiumBps uint16 `json:"premiumBps"`
}

func (obj GeoPremium) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `RegionCode`:
	err = encoder.Encode(obj.RegionCode)
	if err != nil {
		return errors.NewField("RegionCode", err)
	}
	// Serialize `PremiumBps`:
	err = encoder.Encode(obj.PremiumBps)
	if err != nil {
		return errors.NewField("PremiumBps", err)
	}
	return nil
}

func (obj GeoPremium) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding GeoPremium: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *GeoPremium) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `RegionCode`:
	err = decoder.Decode(&obj.RegionCode)
	if err != nil {
		return errors.NewField("RegionCode", err)
	}
	// Deserialize `PremiumBps`:
	err = decoder.Decode(&obj.PremiumBps)
	if err != nil {
		return errors.NewField("PremiumBps", err)
	}
	return nil
}

func (obj *GeoPremium) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling GeoPremium: %w", err)
	}
	return nil
}

func UnmarshalGeoPremium(buf []byte) (*GeoPremium, error) {
	obj := new(GeoPremium)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type PremiumPoolRankingsUpdated struct {
	Updater         solanago.PublicKey `json:"updater"`
	TopWardensCount uint32             `json:"topWardensCount"`
}

func (obj PremiumPoolRankingsUpdated) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Updater`:
	err = encoder.Encode(obj.Updater)
	if err != nil {
		return errors.NewField("Updater", err)
	}
	// Serialize `TopWardensCount`:
	err = encoder.Encode(obj.TopWardensCount)
	if err != nil {
		return errors.NewField("TopWardensCount", err)
	}
	return nil
}

func (obj PremiumPoolRankingsUpdated) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PremiumPoolRankingsUpdated: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PremiumPoolRankingsUpdated) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Updater`:
	err = decoder.Decode(&obj.Updater)
	if err != nil {
		return errors.NewField("Updater", err)
	}
	// Deserialize `TopWardensCount`:
	err = decoder.Decode(&obj.TopWardensCount)
	if err != nil {
		return errors.NewField("TopWardensCount", err)
	}
	return nil
}

func (obj *PremiumPoolRankingsUpdated) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PremiumPoolRankingsUpdated: %w", err)
	}
	return nil
}

func UnmarshalPremiumPoolRankingsUpdated(buf []byte) (*PremiumPoolRankingsUpdated, error) {
	obj := new(PremiumPoolRankingsUpdated)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ProtocolConfig struct {
	Authority         solanago.PublicKey `json:"authority"`
	Treasury          solanago.PublicKey `json:"treasury"`
	ArkhamTokenMint   solanago.PublicKey `json:"arkhamTokenMint"`
	OracleAuthority   solanago.PublicKey `json:"oracleAuthority"`
	BaseRatePerMb     uint64             `json:"baseRatePerMb"`
	ProtocolFeeBps    uint16             `json:"protocolFeeBps"`
	TierThresholds    [3]uint64          `json:"tierThresholds"`
	TierMultipliers   [3]uint16          `json:"tierMultipliers"`
	TokensPer5gb      uint64             `json:"tokensPer5gb"`
	GeoPremiums       []GeoPremium       `json:"geoPremiums"`
	ReputationUpdater solanago.PublicKey `json:"reputationUpdater"`
}

func (obj ProtocolConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `Treasury`:
	err = encoder.Encode(obj.Treasury)
	if err != nil {
		return errors.NewField("Treasury", err)
	}
	// Serialize `ArkhamTokenMint`:
	err = encoder.Encode(obj.ArkhamTokenMint)
	if err != nil {
		return errors.NewField("ArkhamTokenMint", err)
	}
	// Serialize `OracleAuthority`:
	err = encoder.Encode(obj.OracleAuthority)
	if err != nil {
		return errors.NewField("OracleAuthority", err)
	}
	// Serialize `BaseRatePerMb`:
	err = encoder.Encode(obj.BaseRatePerMb)
	if err != nil {
		return errors.NewField("BaseRatePerMb", err)
	}
	// Serialize `ProtocolFeeBps`:
	err = encoder.Encode(obj.ProtocolFeeBps)
	if err != nil {
		return errors.NewField("ProtocolFeeBps", err)
	}
	// Serialize `TierThresholds`:
	err = encoder.Encode(obj.TierThresholds)
	if err != nil {
		return errors.NewField("TierThresholds", err)
	}
	// Serialize `TierMultipliers`:
	err = encoder.Encode(obj.TierMultipliers)
	if err != nil {
		return errors.NewField("TierMultipliers", err)
	}
	// Serialize `TokensPer5gb`:
	err = encoder.Encode(obj.TokensPer5gb)
	if err != nil {
		return errors.NewField("TokensPer5gb", err)
	}
	// Serialize `GeoPremiums`:
	err = encoder.Encode(obj.GeoPremiums)
	if err != nil {
		return errors.NewField("GeoPremiums", err)
	}
	// Serialize `ReputationUpdater`:
	err = encoder.Encode(obj.ReputationUpdater)
	if err != nil {
		return errors.NewField("ReputationUpdater", err)
	}
	return nil
}

func (obj ProtocolConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ProtocolConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ProtocolConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `Treasury`:
	err = decoder.Decode(&obj.Treasury)
	if err != nil {
		return errors.NewField("Treasury", err)
	}
	// Deserialize `ArkhamTokenMint`:
	err = decoder.Decode(&obj.ArkhamTokenMint)
	if err != nil {
		return errors.NewField("ArkhamTokenMint", err)
	}
	// Deserialize `OracleAuthority`:
	err = decoder.Decode(&obj.OracleAuthority)
	if err != nil {
		return errors.NewField("OracleAuthority", err)
	}
	// Deserialize `BaseRatePerMb`:
	err = decoder.Decode(&obj.BaseRatePerMb)
	if err != nil {
		return errors.NewField("BaseRatePerMb", err)
	}
	// Deserialize `ProtocolFeeBps`:
	err = decoder.Decode(&obj.ProtocolFeeBps)
	if err != nil {
		return errors.NewField("ProtocolFeeBps", err)
	}
	// Deserialize `TierThresholds`:
	err = decoder.Decode(&obj.TierThresholds)
	if err != nil {
		return errors.NewField("TierThresholds", err)
	}
	// Deserialize `TierMultipliers`:
	err = decoder.Decode(&obj.TierMultipliers)
	if err != nil {
		return errors.NewField("TierMultipliers", err)
	}
	// Deserialize `TokensPer5gb`:
	err = decoder.Decode(&obj.TokensPer5gb)
	if err != nil {
		return errors.NewField("TokensPer5gb", err)
	}
	// Deserialize `GeoPremiums`:
	err = decoder.Decode(&obj.GeoPremiums)
	if err != nil {
		return errors.NewField("GeoPremiums", err)
	}
	// Deserialize `ReputationUpdater`:
	err = decoder.Decode(&obj.ReputationUpdater)
	if err != nil {
		return errors.NewField("ReputationUpdater", err)
	}
	return nil
}

func (obj *ProtocolConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ProtocolConfig: %w", err)
	}
	return nil
}

func UnmarshalProtocolConfig(buf []byte) (*ProtocolConfig, error) {
	obj := new(ProtocolConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ProtocolConfigInitialized struct {
	Authority      solanago.PublicKey `json:"authority"`
	BaseRatePerMb  uint64             `json:"baseRatePerMb"`
	ProtocolFeeBps uint16             `json:"protocolFeeBps"`
}

func (obj ProtocolConfigInitialized) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `BaseRatePerMb`:
	err = encoder.Encode(obj.BaseRatePerMb)
	if err != nil {
		return errors.NewField("BaseRatePerMb", err)
	}
	// Serialize `ProtocolFeeBps`:
	err = encoder.Encode(obj.ProtocolFeeBps)
	if err != nil {
		return errors.NewField("ProtocolFeeBps", err)
	}
	return nil
}

func (obj ProtocolConfigInitialized) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ProtocolConfigInitialized: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ProtocolConfigInitialized) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `BaseRatePerMb`:
	err = decoder.Decode(&obj.BaseRatePerMb)
	if err != nil {
		return errors.NewField("BaseRatePerMb", err)
	}
	// Deserialize `ProtocolFeeBps`:
	err = decoder.Decode(&obj.ProtocolFeeBps)
	if err != nil {
		return errors.NewField("ProtocolFeeBps", err)
	}
	return nil
}

func (obj *ProtocolConfigInitialized) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ProtocolConfigInitialized: %w", err)
	}
	return nil
}

func UnmarshalProtocolConfigInitialized(buf []byte) (*ProtocolConfigInitialized, error) {
	obj := new(ProtocolConfigInitialized)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ProtocolConfigUpdated struct {
	Authority          solanago.PublicKey `json:"authority"`
	NewBaseRatePerMb   *uint64            `bin:"optional" json:"newBaseRatePerMb,omitempty"`
	NewProtocolFeeBps  *uint16            `bin:"optional" json:"newProtocolFeeBps,omitempty"`
	NewTierThresholds  *[3]uint64         `bin:"optional" json:"newTierThresholds,omitempty"`
	NewTierMultipliers *[3]uint16         `bin:"optional" json:"newTierMultipliers,omitempty"`
	NewTokensPer5gb    *uint64            `bin:"optional" json:"newTokensPer5gb,omitempty"`
}

func (obj ProtocolConfigUpdated) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `NewBaseRatePerMb` (optional):
	{
		if obj.NewBaseRatePerMb == nil {
			err = encoder.WriteOption(false)
			if err != nil {
				return errors.NewOption("NewBaseRatePerMb", fmt.Errorf("error while encoding optionality: %w", err))
			}
		} else {
			err = encoder.WriteOption(true)
			if err != nil {
				return errors.NewOption("NewBaseRatePerMb", fmt.Errorf("error while encoding optionality: %w", err))
			}
			err = encoder.Encode(obj.NewBaseRatePerMb)
			if err != nil {
				return errors.NewField("NewBaseRatePerMb", err)
			}
		}
	}
	// Serialize `NewProtocolFeeBps` (optional):
	{
		if obj.NewProtocolFeeBps == nil {
			err = encoder.WriteOption(false)
			if err != nil {
				return errors.NewOption("NewProtocolFeeBps", fmt.Errorf("error while encoding optionality: %w", err))
			}
		} else {
			err = encoder.WriteOption(true)
			if err != nil {
				return errors.NewOption("NewProtocolFeeBps", fmt.Errorf("error while encoding optionality: %w", err))
			}
			err = encoder.Encode(obj.NewProtocolFeeBps)
			if err != nil {
				return errors.NewField("NewProtocolFeeBps", err)
			}
		}
	}
	// Serialize `NewTierThresholds` (optional):
	{
		if obj.NewTierThresholds == nil {
			err = encoder.WriteOption(false)
			if err != nil {
				return errors.NewOption("NewTierThresholds", fmt.Errorf("error while encoding optionality: %w", err))
			}
		} else {
			err = encoder.WriteOption(true)
			if err != nil {
				return errors.NewOption("NewTierThresholds", fmt.Errorf("error while encoding optionality: %w", err))
			}
			err = encoder.Encode(obj.NewTierThresholds)
			if err != nil {
				return errors.NewField("NewTierThresholds", err)
			}
		}
	}
	// Serialize `NewTierMultipliers` (optional):
	{
		if obj.NewTierMultipliers == nil {
			err = encoder.WriteOption(false)
			if err != nil {
				return errors.NewOption("NewTierMultipliers", fmt.Errorf("error while encoding optionality: %w", err))
			}
		} else {
			err = encoder.WriteOption(true)
			if err != nil {
				return errors.NewOption("NewTierMultipliers", fmt.Errorf("error while encoding optionality: %w", err))
			}
			err = encoder.Encode(obj.NewTierMultipliers)
			if err != nil {
				return errors.NewField("NewTierMultipliers", err)
			}
		}
	}
	// Serialize `NewTokensPer5gb` (optional):
	{
		if obj.NewTokensPer5gb == nil {
			err = encoder.WriteOption(false)
			if err != nil {
				return errors.NewOption("NewTokensPer5gb", fmt.Errorf("error while encoding optionality: %w", err))
			}
		} else {
			err = encoder.WriteOption(true)
			if err != nil {
				return errors.NewOption("NewTokensPer5gb", fmt.Errorf("error while encoding optionality: %w", err))
			}
			err = encoder.Encode(obj.NewTokensPer5gb)
			if err != nil {
				return errors.NewField("NewTokensPer5gb", err)
			}
		}
	}
	return nil
}

func (obj ProtocolConfigUpdated) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ProtocolConfigUpdated: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ProtocolConfigUpdated) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `NewBaseRatePerMb` (optional):
	{
		ok, err := decoder.ReadOption()
		if err != nil {
			return errors.NewOption("NewBaseRatePerMb", fmt.Errorf("error while reading optionality: %w", err))
		}
		if ok {
			err = decoder.Decode(&obj.NewBaseRatePerMb)
			if err != nil {
				return errors.NewField("NewBaseRatePerMb", err)
			}
		}
	}
	// Deserialize `NewProtocolFeeBps` (optional):
	{
		ok, err := decoder.ReadOption()
		if err != nil {
			return errors.NewOption("NewProtocolFeeBps", fmt.Errorf("error while reading optionality: %w", err))
		}
		if ok {
			err = decoder.Decode(&obj.NewProtocolFeeBps)
			if err != nil {
				return errors.NewField("NewProtocolFeeBps", err)
			}
		}
	}
	// Deserialize `NewTierThresholds` (optional):
	{
		ok, err := decoder.ReadOption()
		if err != nil {
			return errors.NewOption("NewTierThresholds", fmt.Errorf("error while reading optionality: %w", err))
		}
		if ok {
			err = decoder.Decode(&obj.NewTierThresholds)
			if err != nil {
				return errors.NewField("NewTierThresholds", err)
			}
		}
	}
	// Deserialize `NewTierMultipliers` (optional):
	{
		ok, err := decoder.ReadOption()
		if err != nil {
			return errors.NewOption("NewTierMultipliers", fmt.Errorf("error while reading optionality: %w", err))
		}
		if ok {
			err = decoder.Decode(&obj.NewTierMultipliers)
			if err != nil {
				return errors.NewField("NewTierMultipliers", err)
			}
		}
	}
	// Deserialize `NewTokensPer5gb` (optional):
	{
		ok, err := decoder.ReadOption()
		if err != nil {
			return errors.NewOption("NewTokensPer5gb", fmt.Errorf("error while reading optionality: %w", err))
		}
		if ok {
			err = decoder.Decode(&obj.NewTokensPer5gb)
			if err != nil {
				return errors.NewField("NewTokensPer5gb", err)
			}
		}
	}
	return nil
}

func (obj *ProtocolConfigUpdated) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ProtocolConfigUpdated: %w", err)
	}
	return nil
}

func UnmarshalProtocolConfigUpdated(buf []byte) (*ProtocolConfigUpdated, error) {
	obj := new(ProtocolConfigUpdated)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ReputationUpdated struct {
	Warden            solanago.PublicKey `json:"warden"`
	NewScore          uint32             `json:"newScore"`
	UptimeReport      uint16             `json:"uptimeReport"`
	ConnectionSuccess bool               `json:"connectionSuccess"`
}

func (obj ReputationUpdated) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Warden`:
	err = encoder.Encode(obj.Warden)
	if err != nil {
		return errors.NewField("Warden", err)
	}
	// Serialize `NewScore`:
	err = encoder.Encode(obj.NewScore)
	if err != nil {
		return errors.NewField("NewScore", err)
	}
	// Serialize `UptimeReport`:
	err = encoder.Encode(obj.UptimeReport)
	if err != nil {
		return errors.NewField("UptimeReport", err)
	}
	// Serialize `ConnectionSuccess`:
	err = encoder.Encode(obj.ConnectionSuccess)
	if err != nil {
		return errors.NewField("ConnectionSuccess", err)
	}
	return nil
}

func (obj ReputationUpdated) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ReputationUpdated: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ReputationUpdated) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Warden`:
	err = decoder.Decode(&obj.Warden)
	if err != nil {
		return errors.NewField("Warden", err)
	}
	// Deserialize `NewScore`:
	err = decoder.Decode(&obj.NewScore)
	if err != nil {
		return errors.NewField("NewScore", err)
	}
	// Deserialize `UptimeReport`:
	err = decoder.Decode(&obj.UptimeReport)
	if err != nil {
		return errors.NewField("UptimeReport", err)
	}
	// Deserialize `ConnectionSuccess`:
	err = decoder.Decode(&obj.ConnectionSuccess)
	if err != nil {
		return errors.NewField("ConnectionSuccess", err)
	}
	return nil
}

func (obj *ReputationUpdated) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ReputationUpdated: %w", err)
	}
	return nil
}

func UnmarshalReputationUpdated(buf []byte) (*ReputationUpdated, error) {
	obj := new(ReputationUpdated)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Seeker struct {
	Authority              solanago.PublicKey  `json:"authority"`
	EscrowBalance          uint64              `json:"escrowBalance"`
	PrivateEscrow          *solanago.PublicKey `bin:"optional" json:"privateEscrow,omitempty"`
	TotalBandwidthConsumed uint64              `json:"totalBandwidthConsumed"`
	TotalSpent             uint64              `json:"totalSpent"`
	ActiveConnections      uint8               `json:"activeConnections"`
	PremiumExpiresAt       *int64              `bin:"optional" json:"premiumExpiresAt,omitempty"`
}

func (obj Seeker) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `EscrowBalance`:
	err = encoder.Encode(obj.EscrowBalance)
	if err != nil {
		return errors.NewField("EscrowBalance", err)
	}
	// Serialize `PrivateEscrow` (optional):
	{
		if obj.PrivateEscrow == nil {
			err = encoder.WriteOption(false)
			if err != nil {
				return errors.NewOption("PrivateEscrow", fmt.Errorf("error while encoding optionality: %w", err))
			}
		} else {
			err = encoder.WriteOption(true)
			if err != nil {
				return errors.NewOption("PrivateEscrow", fmt.Errorf("error while encoding optionality: %w", err))
			}
			err = encoder.Encode(obj.PrivateEscrow)
			if err != nil {
				return errors.NewField("PrivateEscrow", err)
			}
		}
	}
	// Serialize `TotalBandwidthConsumed`:
	err = encoder.Encode(obj.TotalBandwidthConsumed)
	if err != nil {
		return errors.NewField("TotalBandwidthConsumed", err)
	}
	// Serialize `TotalSpent`:
	err = encoder.Encode(obj.TotalSpent)
	if err != nil {
		return errors.NewField("TotalSpent", err)
	}
	// Serialize `ActiveConnections`:
	err = encoder.Encode(obj.ActiveConnections)
	if err != nil {
		return errors.NewField("ActiveConnections", err)
	}
	// Serialize `PremiumExpiresAt` (optional):
	{
		if obj.PremiumExpiresAt == nil {
			err = encoder.WriteOption(false)
			if err != nil {
				return errors.NewOption("PremiumExpiresAt", fmt.Errorf("error while encoding optionality: %w", err))
			}
		} else {
			err = encoder.WriteOption(true)
			if err != nil {
				return errors.NewOption("PremiumExpiresAt", fmt.Errorf("error while encoding optionality: %w", err))
			}
			err = encoder.Encode(obj.PremiumExpiresAt)
			if err != nil {
				return errors.NewField("PremiumExpiresAt", err)
			}
		}
	}
	return nil
}

func (obj Seeker) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Seeker: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Seeker) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `EscrowBalance`:
	err = decoder.Decode(&obj.EscrowBalance)
	if err != nil {
		return errors.NewField("EscrowBalance", err)
	}
	// Deserialize `PrivateEscrow` (optional):
	{
		ok, err := decoder.ReadOption()
		if err != nil {
			return errors.NewOption("PrivateEscrow", fmt.Errorf("error while reading optionality: %w", err))
		}
		if ok {
			err = decoder.Decode(&obj.PrivateEscrow)
			if err != nil {
				return errors.NewField("PrivateEscrow", err)
			}
		}
	}
	// Deserialize `TotalBandwidthConsumed`:
	err = decoder.Decode(&obj.TotalBandwidthConsumed)
	if err != nil {
		return errors.NewField("TotalBandwidthConsumed", err)
	}
	// Deserialize `TotalSpent`:
	err = decoder.Decode(&obj.TotalSpent)
	if err != nil {
		return errors.NewField("TotalSpent", err)
	}
	// Deserialize `ActiveConnections`:
	err = decoder.Decode(&obj.ActiveConnections)
	if err != nil {
		return errors.NewField("ActiveConnections", err)
	}
	// Deserialize `PremiumExpiresAt` (optional):
	{
		ok, err := decoder.ReadOption()
		if err != nil {
			return errors.NewOption("PremiumExpiresAt", fmt.Errorf("error while reading optionality: %w", err))
		}
		if ok {
			err = decoder.Decode(&obj.PremiumExpiresAt)
			if err != nil {
				return errors.NewField("PremiumExpiresAt", err)
			}
		}
	}
	return nil
}

func (obj *Seeker) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Seeker: %w", err)
	}
	return nil
}

func UnmarshalSeeker(buf []byte) (*Seeker, error) {
	obj := new(Seeker)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type StakeToken binary.BorshEnum

const (
	StakeToken_Sol StakeToken = iota
	StakeToken_Usdc
	StakeToken_Usdt
)

func (value StakeToken) String() string {
	switch value {
	case StakeToken_Sol:
		return "Sol"
	case StakeToken_Usdc:
		return "Usdc"
	case StakeToken_Usdt:
		return "Usdt"
	default:
		return ""
	}
}

type SubsidiesDistributed struct {
	Authority   solanago.PublicKey `json:"authority"`
	WardenCount uint32             `json:"wardenCount"`
	TotalAmount uint64             `json:"totalAmount"`
}

func (obj SubsidiesDistributed) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `WardenCount`:
	err = encoder.Encode(obj.WardenCount)
	if err != nil {
		return errors.NewField("WardenCount", err)
	}
	// Serialize `TotalAmount`:
	err = encoder.Encode(obj.TotalAmount)
	if err != nil {
		return errors.NewField("TotalAmount", err)
	}
	return nil
}

func (obj SubsidiesDistributed) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SubsidiesDistributed: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SubsidiesDistributed) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `WardenCount`:
	err = decoder.Decode(&obj.WardenCount)
	if err != nil {
		return errors.NewField("WardenCount", err)
	}
	// Deserialize `TotalAmount`:
	err = decoder.Decode(&obj.TotalAmount)
	if err != nil {
		return errors.NewField("TotalAmount", err)
	}
	return nil
}

func (obj *SubsidiesDistributed) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SubsidiesDistributed: %w", err)
	}
	return nil
}

func UnmarshalSubsidiesDistributed(buf []byte) (*SubsidiesDistributed, error) {
	obj := new(SubsidiesDistributed)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Tier binary.BorshEnum

const (
	Tier_Bronze Tier = iota
	Tier_Silver
	Tier_Gold
)

func (value Tier) String() string {
	switch value {
	case Tier_Bronze:
		return "Bronze"
	case Tier_Silver:
		return "Silver"
	case Tier_Gold:
		return "Gold"
	default:
		return ""
	}
}

type TokensClaimed struct {
	Authority solanago.PublicKey `json:"authority"`
	Amount    uint64             `json:"amount"`
}

func (obj TokensClaimed) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `Amount`:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	return nil
}

func (obj TokensClaimed) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TokensClaimed: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TokensClaimed) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	return nil
}

func (obj *TokensClaimed) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TokensClaimed: %w", err)
	}
	return nil
}

func UnmarshalTokensClaimed(buf []byte) (*TokensClaimed, error) {
	obj := new(TokensClaimed)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type UnstakeRequested struct {
	Authority   solanago.PublicKey `json:"authority"`
	RequestedAt int64              `json:"requestedAt"`
}

func (obj UnstakeRequested) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `RequestedAt`:
	err = encoder.Encode(obj.RequestedAt)
	if err != nil {
		return errors.NewField("RequestedAt", err)
	}
	return nil
}

func (obj UnstakeRequested) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding UnstakeRequested: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *UnstakeRequested) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `RequestedAt`:
	err = decoder.Decode(&obj.RequestedAt)
	if err != nil {
		return errors.NewField("RequestedAt", err)
	}
	return nil
}

func (obj *UnstakeRequested) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling UnstakeRequested: %w", err)
	}
	return nil
}

func UnmarshalUnstakeRequested(buf []byte) (*UnstakeRequested, error) {
	obj := new(UnstakeRequested)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Warden struct {
	Authority             solanago.PublicKey `json:"authority"`
	PeerId                string             `json:"peerId"`
	StakeToken            StakeToken         `json:"stakeToken"`
	StakeAmount           uint64             `json:"stakeAmount"`
	StakeValueUsd         uint64             `json:"stakeValueUsd"`
	Tier                  Tier               `json:"tier"`
	StakedAt              int64              `json:"stakedAt"`
	UnstakeRequestedAt    *int64             `bin:"optional" json:"unstakeRequestedAt,omitempty"`
	TotalBandwidthServed  uint64             `json:"totalBandwidthServed"`
	TotalEarnings         uint64             `json:"totalEarnings"`
	PendingClaims         uint64             `json:"pendingClaims"`
	ArkhamTokensEarned    uint64             `json:"arkhamTokensEarned"`
	ReputationScore       uint32             `json:"reputationScore"`
	SuccessfulConnections uint64             `json:"successfulConnections"`
	FailedConnections     uint64             `json:"failedConnections"`
	UptimePercentage      uint16             `json:"uptimePercentage"`
	LastActive            int64              `json:"lastActive"`
	RegionCode            uint8              `json:"regionCode"`
	IpHash                [32]uint8          `json:"ipHash"`
	PremiumPoolRank       *uint16            `bin:"optional" json:"premiumPoolRank,omitempty"`
	ActiveConnections     uint8              `json:"activeConnections"`
}

func (obj Warden) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `PeerId`:
	err = encoder.Encode(obj.PeerId)
	if err != nil {
		return errors.NewField("PeerId", err)
	}
	// Serialize `StakeToken`:
	err = encoder.Encode(obj.StakeToken)
	if err != nil {
		return errors.NewField("StakeToken", err)
	}
	// Serialize `StakeAmount`:
	err = encoder.Encode(obj.StakeAmount)
	if err != nil {
		return errors.NewField("StakeAmount", err)
	}
	// Serialize `StakeValueUsd`:
	err = encoder.Encode(obj.StakeValueUsd)
	if err != nil {
		return errors.NewField("StakeValueUsd", err)
	}
	// Serialize `Tier`:
	err = encoder.Encode(obj.Tier)
	if err != nil {
		return errors.NewField("Tier", err)
	}
	// Serialize `StakedAt`:
	err = encoder.Encode(obj.StakedAt)
	if err != nil {
		return errors.NewField("StakedAt", err)
	}
	// Serialize `UnstakeRequestedAt` (optional):
	{
		if obj.UnstakeRequestedAt == nil {
			err = encoder.WriteOption(false)
			if err != nil {
				return errors.NewOption("UnstakeRequestedAt", fmt.Errorf("error while encoding optionality: %w", err))
			}
		} else {
			err = encoder.WriteOption(true)
			if err != nil {
				return errors.NewOption("UnstakeRequestedAt", fmt.Errorf("error while encoding optionality: %w", err))
			}
			err = encoder.Encode(obj.UnstakeRequestedAt)
			if err != nil {
				return errors.NewField("UnstakeRequestedAt", err)
			}
		}
	}
	// Serialize `TotalBandwidthServed`:
	err = encoder.Encode(obj.TotalBandwidthServed)
	if err != nil {
		return errors.NewField("TotalBandwidthServed", err)
	}
	// Serialize `TotalEarnings`:
	err = encoder.Encode(obj.TotalEarnings)
	if err != nil {
		return errors.NewField("TotalEarnings", err)
	}
	// Serialize `PendingClaims`:
	err = encoder.Encode(obj.PendingClaims)
	if err != nil {
		return errors.NewField("PendingClaims", err)
	}
	// Serialize `ArkhamTokensEarned`:
	err = encoder.Encode(obj.ArkhamTokensEarned)
	if err != nil {
		return errors.NewField("ArkhamTokensEarned", err)
	}
	// Serialize `ReputationScore`:
	err = encoder.Encode(obj.ReputationScore)
	if err != nil {
		return errors.NewField("ReputationScore", err)
	}
	// Serialize `SuccessfulConnections`:
	err = encoder.Encode(obj.SuccessfulConnections)
	if err != nil {
		return errors.NewField("SuccessfulConnections", err)
	}
	// Serialize `FailedConnections`:
	err = encoder.Encode(obj.FailedConnections)
	if err != nil {
		return errors.NewField("FailedConnections", err)
	}
	// Serialize `UptimePercentage`:
	err = encoder.Encode(obj.UptimePercentage)
	if err != nil {
		return errors.NewField("UptimePercentage", err)
	}
	// Serialize `LastActive`:
	err = encoder.Encode(obj.LastActive)
	if err != nil {
		return errors.NewField("LastActive", err)
	}
	// Serialize `RegionCode`:
	err = encoder.Encode(obj.RegionCode)
	if err != nil {
		return errors.NewField("RegionCode", err)
	}
	// Serialize `IpHash`:
	err = encoder.Encode(obj.IpHash)
	if err != nil {
		return errors.NewField("IpHash", err)
	}
	// Serialize `PremiumPoolRank` (optional):
	{
		if obj.PremiumPoolRank == nil {
			err = encoder.WriteOption(false)
			if err != nil {
				return errors.NewOption("PremiumPoolRank", fmt.Errorf("error while encoding optionality: %w", err))
			}
		} else {
			err = encoder.WriteOption(true)
			if err != nil {
				return errors.NewOption("PremiumPoolRank", fmt.Errorf("error while encoding optionality: %w", err))
			}
			err = encoder.Encode(obj.PremiumPoolRank)
			if err != nil {
				return errors.NewField("PremiumPoolRank", err)
			}
		}
	}
	// Serialize `ActiveConnections`:
	err = encoder.Encode(obj.ActiveConnections)
	if err != nil {
		return errors.NewField("ActiveConnections", err)
	}
	return nil
}

func (obj Warden) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Warden: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Warden) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `PeerId`:
	err = decoder.Decode(&obj.PeerId)
	if err != nil {
		return errors.NewField("PeerId", err)
	}
	// Deserialize `StakeToken`:
	err = decoder.Decode(&obj.StakeToken)
	if err != nil {
		return errors.NewField("StakeToken", err)
	}
	// Deserialize `StakeAmount`:
	err = decoder.Decode(&obj.StakeAmount)
	if err != nil {
		return errors.NewField("StakeAmount", err)
	}
	// Deserialize `StakeValueUsd`:
	err = decoder.Decode(&obj.StakeValueUsd)
	if err != nil {
		return errors.NewField("StakeValueUsd", err)
	}
	// Deserialize `Tier`:
	err = decoder.Decode(&obj.Tier)
	if err != nil {
		return errors.NewField("Tier", err)
	}
	// Deserialize `StakedAt`:
	err = decoder.Decode(&obj.StakedAt)
	if err != nil {
		return errors.NewField("StakedAt", err)
	}
	// Deserialize `UnstakeRequestedAt` (optional):
	{
		ok, err := decoder.ReadOption()
		if err != nil {
			return errors.NewOption("UnstakeRequestedAt", fmt.Errorf("error while reading optionality: %w", err))
		}
		if ok {
			err = decoder.Decode(&obj.UnstakeRequestedAt)
			if err != nil {
				return errors.NewField("UnstakeRequestedAt", err)
			}
		}
	}
	// Deserialize `TotalBandwidthServed`:
	err = decoder.Decode(&obj.TotalBandwidthServed)
	if err != nil {
		return errors.NewField("TotalBandwidthServed", err)
	}
	// Deserialize `TotalEarnings`:
	err = decoder.Decode(&obj.TotalEarnings)
	if err != nil {
		return errors.NewField("TotalEarnings", err)
	}
	// Deserialize `PendingClaims`:
	err = decoder.Decode(&obj.PendingClaims)
	if err != nil {
		return errors.NewField("PendingClaims", err)
	}
	// Deserialize `ArkhamTokensEarned`:
	err = decoder.Decode(&obj.ArkhamTokensEarned)
	if err != nil {
		return errors.NewField("ArkhamTokensEarned", err)
	}
	// Deserialize `ReputationScore`:
	err = decoder.Decode(&obj.ReputationScore)
	if err != nil {
		return errors.NewField("ReputationScore", err)
	}
	// Deserialize `SuccessfulConnections`:
	err = decoder.Decode(&obj.SuccessfulConnections)
	if err != nil {
		return errors.NewField("SuccessfulConnections", err)
	}
	// Deserialize `FailedConnections`:
	err = decoder.Decode(&obj.FailedConnections)
	if err != nil {
		return errors.NewField("FailedConnections", err)
	}
	// Deserialize `UptimePercentage`:
	err = decoder.Decode(&obj.UptimePercentage)
	if err != nil {
		return errors.NewField("UptimePercentage", err)
	}
	// Deserialize `LastActive`:
	err = decoder.Decode(&obj.LastActive)
	if err != nil {
		return errors.NewField("LastActive", err)
	}
	// Deserialize `RegionCode`:
	err = decoder.Decode(&obj.RegionCode)
	if err != nil {
		return errors.NewField("RegionCode", err)
	}
	// Deserialize `IpHash`:
	err = decoder.Decode(&obj.IpHash)
	if err != nil {
		return errors.NewField("IpHash", err)
	}
	// Deserialize `PremiumPoolRank` (optional):
	{
		ok, err := decoder.ReadOption()
		if err != nil {
			return errors.NewOption("PremiumPoolRank", fmt.Errorf("error while reading optionality: %w", err))
		}
		if ok {
			err = decoder.Decode(&obj.PremiumPoolRank)
			if err != nil {
				return errors.NewField("PremiumPoolRank", err)
			}
		}
	}
	// Deserialize `ActiveConnections`:
	err = decoder.Decode(&obj.ActiveConnections)
	if err != nil {
		return errors.NewField("ActiveConnections", err)
	}
	return nil
}

func (obj *Warden) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Warden: %w", err)
	}
	return nil
}

func UnmarshalWarden(buf []byte) (*Warden, error) {
	obj := new(Warden)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type WardenPeerIdUpdated struct {
	WardenAuthority solanago.PublicKey `json:"wardenAuthority"`
	OldPeerId       string             `json:"oldPeerId"`
	NewPeerId       string             `json:"newPeerId"`
}

func (obj WardenPeerIdUpdated) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `WardenAuthority`:
	err = encoder.Encode(obj.WardenAuthority)
	if err != nil {
		return errors.NewField("WardenAuthority", err)
	}
	// Serialize `OldPeerId`:
	err = encoder.Encode(obj.OldPeerId)
	if err != nil {
		return errors.NewField("OldPeerId", err)
	}
	// Serialize `NewPeerId`:
	err = encoder.Encode(obj.NewPeerId)
	if err != nil {
		return errors.NewField("NewPeerId", err)
	}
	return nil
}

func (obj WardenPeerIdUpdated) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding WardenPeerIdUpdated: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *WardenPeerIdUpdated) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `WardenAuthority`:
	err = decoder.Decode(&obj.WardenAuthority)
	if err != nil {
		return errors.NewField("WardenAuthority", err)
	}
	// Deserialize `OldPeerId`:
	err = decoder.Decode(&obj.OldPeerId)
	if err != nil {
		return errors.NewField("OldPeerId", err)
	}
	// Deserialize `NewPeerId`:
	err = decoder.Decode(&obj.NewPeerId)
	if err != nil {
		return errors.NewField("NewPeerId", err)
	}
	return nil
}

func (obj *WardenPeerIdUpdated) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling WardenPeerIdUpdated: %w", err)
	}
	return nil
}

func UnmarshalWardenPeerIdUpdated(buf []byte) (*WardenPeerIdUpdated, error) {
	obj := new(WardenPeerIdUpdated)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type WardenRegistered struct {
	Authority   solanago.PublicKey `json:"authority"`
	Tier        Tier               `json:"tier"`
	StakeAmount uint64             `json:"stakeAmount"`
	StakeToken  StakeToken         `json:"stakeToken"`
}

func (obj WardenRegistered) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `Tier`:
	err = encoder.Encode(obj.Tier)
	if err != nil {
		return errors.NewField("Tier", err)
	}
	// Serialize `StakeAmount`:
	err = encoder.Encode(obj.StakeAmount)
	if err != nil {
		return errors.NewField("StakeAmount", err)
	}
	// Serialize `StakeToken`:
	err = encoder.Encode(obj.StakeToken)
	if err != nil {
		return errors.NewField("StakeToken", err)
	}
	return nil
}

func (obj WardenRegistered) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding WardenRegistered: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *WardenRegistered) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `Tier`:
	err = decoder.Decode(&obj.Tier)
	if err != nil {
		return errors.NewField("Tier", err)
	}
	// Deserialize `StakeAmount`:
	err = decoder.Decode(&obj.StakeAmount)
	if err != nil {
		return errors.NewField("StakeAmount", err)
	}
	// Deserialize `StakeToken`:
	err = decoder.Decode(&obj.StakeToken)
	if err != nil {
		return errors.NewField("StakeToken", err)
	}
	return nil
}

func (obj *WardenRegistered) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling WardenRegistered: %w", err)
	}
	return nil
}

func UnmarshalWardenRegistered(buf []byte) (*WardenRegistered, error) {
	obj := new(WardenRegistered)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type WardenUnstaked struct {
	Authority   solanago.PublicKey `json:"authority"`
	StakeAmount uint64             `json:"stakeAmount"`
	StakeToken  StakeToken         `json:"stakeToken"`
}

func (obj WardenUnstaked) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `StakeAmount`:
	err = encoder.Encode(obj.StakeAmount)
	if err != nil {
		return errors.NewField("StakeAmount", err)
	}
	// Serialize `StakeToken`:
	err = encoder.Encode(obj.StakeToken)
	if err != nil {
		return errors.NewField("StakeToken", err)
	}
	return nil
}

func (obj WardenUnstaked) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding WardenUnstaked: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *WardenUnstaked) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `StakeAmount`:
	err = decoder.Decode(&obj.StakeAmount)
	if err != nil {
		return errors.NewField("StakeAmount", err)
	}
	// Deserialize `StakeToken`:
	err = decoder.Decode(&obj.StakeToken)
	if err != nil {
		return errors.NewField("StakeToken", err)
	}
	return nil
}

func (obj *WardenUnstaked) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling WardenUnstaked: %w", err)
	}
	return nil
}

func UnmarshalWardenUnstaked(buf []byte) (*WardenUnstaked, error) {
	obj := new(WardenUnstaked)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
